#! /bin/sh

bspc config border_width        2
bspc config window_gap        	20 

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color '#9a2f28'

bspc config normal_border_color  '#081f2d'

bspc config presel_border_color  '#599caa'
